#|
Файл конфигурации для системы управления задачами
Содержит настройки задач и их параметров
|#

task1 = "Разработка функционала"
priority1 = 1
estimate_hours = 5

task2 = "Тестирование системы"
priority2 = 2
estimate_hours2 = .[estimate_hours 2 +].

task_list = [ "Разработка", "Тестирование", "Деплой" ]
